# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(
      type: "appstore",
      git_url: "ssh://swasth/v1/repos/swasth-apps-codesign"
    ) # more information: https://codesigning.guide   
    increment_build_number(xcodeproj: "DBTCoach.xcodeproj")
    build_app(scheme: "DBTCoach")
    upload_to_testflight
    upload_symbols_to_bugsnag
  end
  lane :refresh_dsyms do
    download_dsyms(version: "2.0.8")     # Download dSYM files from iTC
    upload_symbols_to_bugsnag              # Upload them to Bugsnag
    clean_build_artifacts                  # Delete the local dSYM files
  end
  
end
